# Generated by Django 5.2.5 on 2025-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='pais',
            field=models.CharField(default='Argentina', max_length=50),
        ),
    ]
