# Generated by Django 5.2.5 on 2025-08-29 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('alimentos', 'Alimentos & Bebidas'), ('estacionamiento', 'Estacionamiento'), ('lavanderia', 'Lavandería'), ('late_checkout', 'Late Check-out'), ('early_checkin', 'Early Check-in'), ('otros', 'Otros')], max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('dia', 'Por día'), ('hora', 'Por hora'), ('persona', 'Por persona'), ('noche', 'Por noche')], default='unidad', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicios_servicio',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('facturado', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'db_table': 'servicios_consumo',
                'ordering': ['-fecha_consumo'],
            },
        ),
    ]
