# Generated by Django 5.2.5 on 2025-08-29 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('es_online', models.BooleanField(default=False)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='% de comisión que te cobra el canal', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Canales de Venta',
                'db_table': 'habitaciones_canalventa',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('max_personas', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'habitaciones_tipo',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('sucia', 'Necesita Limpieza')], default='disponible', max_length=15)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.tipohabitacion')),
            ],
            options={
                'db_table': 'habitaciones_habitacion',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='habitaciones.canalventa')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='habitaciones.tipohabitacion')),
            ],
            options={
                'db_table': 'habitaciones_tarifa',
                'ordering': ['tipo_habitacion', 'canal', '-fecha_inicio'],
                'unique_together': {('tipo_habitacion', 'canal', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
