# Generated by Django 5.2.5 on 2025-08-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente Confirmación'), ('confirmada', 'Confirmada'), ('check_in', 'Check-in Realizado'), ('check_out', 'Check-out Realizado'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendiente', max_length=20)),
                ('adultos', models.PositiveIntegerField(default=1)),
                ('ninos', models.PositiveIntegerField(default=0)),
                ('comentarios', models.TextField(blank=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huespedes.huesped')),
            ],
            options={
                'db_table': 'reservas_reserva',
            },
        ),
        migrations.CreateModel(
            name='HuespedAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='reservas.reserva')),
            ],
            options={
                'db_table': 'reservas_huespedadicional',
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_entrada', 'fecha_salida'], name='reservas_re_fecha_e_bd65ab_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
    ]
